// lib/products.js

export const products = [
  {
    id: 'lmn-001',
    slug: 'luminal-serum',
    sku: 'LMN-SRM-30',
    name: 'Luminal Serum',
    subtitle: 'Radiance-activating concentrate',
    price: 148,
    comparePrice: 185,
    categories: ['Serums', 'Brightening'],
    badge: 'Bestseller',
    description: 'A silky, fast-absorbing serum that delivers a potent blend of stabilised Vitamin C, Niacinamide, and Bakuchiol directly into skin. Clinically proven to reduce dark spots by 43% in 8 weeks.',
    details: ['30ml / 1.0 fl oz', 'Fragrance-free', 'Suitable for all skin types', 'Dermatologist tested', 'Vegan & cruelty-free'],
    ingredients: 'Aqua, Ascorbic Acid 15%, Niacinamide 10%, Bakuchiol 1%, Hyaluronic Acid, Pentylene Glycol, Squalane',
    howToUse: 'Apply 4–5 drops to cleansed skin every morning. Follow with SPF. Use twice daily for accelerated results.',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=90',
    images: [
      'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=90',
      'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=90',
      'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&q=90',
    ],
    reviews: 4.9,
    reviewCount: 2847,
  },
  {
    id: 'lmn-002',
    slug: 'velour-moisturiser',
    sku: 'LMN-MST-50',
    name: 'Velour Moisturiser',
    subtitle: 'Barrier-restoring cream',
    price: 96,
    comparePrice: null,
    categories: ['Moisturisers', 'Barrier Repair'],
    badge: 'New',
    description: 'A weightless yet deeply nourishing moisturiser formulated with Ceramide Complex, Snow Mushroom, and Peptide-9. Rebuilds and strengthens the skin barrier while delivering 72-hour hydration.',
    details: ['50ml / 1.7 fl oz', 'Lightly fragranced with neroli', 'All skin types, ideal for dry & sensitive', 'Clinically tested', 'Vegan & cruelty-free'],
    ingredients: 'Aqua, Ceramide NP, Ceramide AP, Ceramide EOP, Tremella Fuciformis Extract, Palmitoyl Tripeptide-1, Shea Butter, Glycerin',
    howToUse: 'Apply morning and night after serum. Massage gently into face and neck using upward strokes.',
    image: 'https://images.unsplash.com/photo-1570194065650-d99fb4b8ccb0?w=800&q=90',
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4b8ccb0?w=800&q=90'],
    reviews: 4.8,
    reviewCount: 1204,
  },
  {
    id: 'lmn-003',
    slug: 'obsidian-cleanser',
    sku: 'LMN-CLN-150',
    name: 'Obsidian Cleanser',
    subtitle: 'Purifying oil-to-milk cleanser',
    price: 68,
    comparePrice: null,
    categories: ['Cleansers'],
    badge: null,
    description: 'Dissolves makeup, SPF, and impurities without stripping. Transforms from a silky oil to a milky emulsion upon contact with water. Black Charcoal and Camellia Oil leave skin balanced and luminous.',
    details: ['150ml / 5.0 fl oz', 'Fragrance-free', 'Normal, oily & combination skin', 'Ophthalmologist tested', 'Vegan & cruelty-free'],
    ingredients: 'Camellia Sinensis Seed Oil, Activated Charcoal, Jojoba Esters, Polysorbate 80, Vitamin E',
    howToUse: 'Massage onto dry skin for 60 seconds. Add water to emulsify. Rinse thoroughly. Use morning and evening.',
    image: 'https://images.unsplash.com/photo-1631390979758-a1b8c45a8db0?w=800&q=90',
    images: ['https://images.unsplash.com/photo-1631390979758-a1b8c45a8db0?w=800&q=90'],
    reviews: 4.7,
    reviewCount: 889,
  },
  {
    id: 'lmn-004',
    slug: 'aureate-eye-cream',
    sku: 'LMN-EYE-15',
    name: 'Aureate Eye Cream',
    subtitle: 'Firming & de-puffing treatment',
    price: 124,
    comparePrice: null,
    categories: ['Eye Care', 'Anti-Ageing'],
    badge: 'Award Winner',
    description: 'An ultra-rich eye cream with Gold Peptide Complex, Caffeine, and Retinyl Palmitate. Visibly reduces dark circles, puffiness, and crow\'s feet in 4 weeks.',
    details: ['15ml / 0.5 fl oz', 'Subtle rose scent', 'All skin types', 'Ophthalmologist tested', 'Vegan & cruelty-free'],
    ingredients: 'Aqua, Gold (Au), Caffeine 2%, Retinyl Palmitate, Palmitoyl Pentapeptide-4, Rosa Damascena Flower Water',
    howToUse: 'Using ring finger, gently tap a small amount around the orbital bone. Use morning and evening.',
    image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&q=90',
    images: ['https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?w=800&q=90'],
    reviews: 4.9,
    reviewCount: 634,
  },
  {
    id: 'lmn-005',
    slug: 'solar-shield-spf50',
    sku: 'LMN-SPF-50',
    name: 'Solar Shield SPF 50',
    subtitle: 'Invisible broad-spectrum sunscreen',
    price: 58,
    comparePrice: null,
    categories: ['Sun Care', 'SPF'],
    badge: 'Essential',
    description: 'A featherlight, no-white-cast sunscreen that doubles as a skincare primer. Zinc Oxide and Tinosorb M provide broad-spectrum UVA/UVB protection. Enriched with Centella Asiatica to calm and protect.',
    details: ['50ml / 1.7 fl oz', 'Fragrance-free', 'All skin types including sensitive', 'Dermatologist tested', 'Vegan & cruelty-free'],
    ingredients: 'Aqua, Zinc Oxide 10%, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Centella Asiatica Extract, Niacinamide 5%',
    howToUse: 'Apply generously as the final step of your morning routine. Reapply every 2 hours when outdoors.',
    image: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=90',
    images: ['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800&q=90'],
    reviews: 4.8,
    reviewCount: 1567,
  },
  {
    id: 'lmn-006',
    slug: 'midnight-mask',
    sku: 'LMN-MSK-75',
    name: 'Midnight Mask',
    subtitle: 'Overnight resurfacing treatment',
    price: 112,
    comparePrice: 140,
    categories: ['Masks', 'Exfoliants'],
    badge: 'Cult Favourite',
    description: 'A luxurious overnight mask that resurfaces while you sleep. A blend of AHA/BHA, Retinol, and Hyaluronic Acid gently exfoliates, refines pores, and delivers deep hydration. Wake up to visibly smoother, clearer skin.',
    details: ['75ml / 2.5 fl oz', 'Light bergamot scent', 'Normal to oily skin', 'Dermatologist tested', 'Vegan & cruelty-free'],
    ingredients: 'Aqua, Glycolic Acid 8%, Salicylic Acid 0.5%, Retinol 0.025%, Sodium Hyaluronate, Centella Asiatica',
    howToUse: 'Apply a thin layer to clean skin 2–3 nights per week as the final step of your evening routine. Do not rinse.',
    image: 'https://images.unsplash.com/photo-1601049541206-3b776ae56e8c?w=800&q=90',
    images: ['https://images.unsplash.com/photo-1601049541206-3b776ae56e8c?w=800&q=90'],
    reviews: 4.9,
    reviewCount: 2103,
  },
];

export const getProduct = (slug) => products.find(p => p.slug === slug);
